/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ShoppingRouteImport } from './routes/shopping'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as MealsRouteImport } from './routes/meals'
import { Route as GoalsRouteImport } from './routes/goals'
import { Route as ChoresRouteImport } from './routes/chores'
import { Route as CalendarRouteImport } from './routes/calendar'
import { Route as AssistantRouteImport } from './routes/assistant'
import { Route as IndexRouteImport } from './routes/index'

const ShoppingRoute = ShoppingRouteImport.update({
  id: '/shopping',
  path: '/shopping',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const MealsRoute = MealsRouteImport.update({
  id: '/meals',
  path: '/meals',
  getParentRoute: () => rootRouteImport,
} as any)
const GoalsRoute = GoalsRouteImport.update({
  id: '/goals',
  path: '/goals',
  getParentRoute: () => rootRouteImport,
} as any)
const ChoresRoute = ChoresRouteImport.update({
  id: '/chores',
  path: '/chores',
  getParentRoute: () => rootRouteImport,
} as any)
const CalendarRoute = CalendarRouteImport.update({
  id: '/calendar',
  path: '/calendar',
  getParentRoute: () => rootRouteImport,
} as any)
const AssistantRoute = AssistantRouteImport.update({
  id: '/assistant',
  path: '/assistant',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/assistant': typeof AssistantRoute
  '/calendar': typeof CalendarRoute
  '/chores': typeof ChoresRoute
  '/goals': typeof GoalsRoute
  '/meals': typeof MealsRoute
  '/settings': typeof SettingsRoute
  '/shopping': typeof ShoppingRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/assistant': typeof AssistantRoute
  '/calendar': typeof CalendarRoute
  '/chores': typeof ChoresRoute
  '/goals': typeof GoalsRoute
  '/meals': typeof MealsRoute
  '/settings': typeof SettingsRoute
  '/shopping': typeof ShoppingRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/assistant': typeof AssistantRoute
  '/calendar': typeof CalendarRoute
  '/chores': typeof ChoresRoute
  '/goals': typeof GoalsRoute
  '/meals': typeof MealsRoute
  '/settings': typeof SettingsRoute
  '/shopping': typeof ShoppingRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/assistant'
    | '/calendar'
    | '/chores'
    | '/goals'
    | '/meals'
    | '/settings'
    | '/shopping'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/assistant'
    | '/calendar'
    | '/chores'
    | '/goals'
    | '/meals'
    | '/settings'
    | '/shopping'
  id:
    | '__root__'
    | '/'
    | '/assistant'
    | '/calendar'
    | '/chores'
    | '/goals'
    | '/meals'
    | '/settings'
    | '/shopping'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AssistantRoute: typeof AssistantRoute
  CalendarRoute: typeof CalendarRoute
  ChoresRoute: typeof ChoresRoute
  GoalsRoute: typeof GoalsRoute
  MealsRoute: typeof MealsRoute
  SettingsRoute: typeof SettingsRoute
  ShoppingRoute: typeof ShoppingRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/shopping': {
      id: '/shopping'
      path: '/shopping'
      fullPath: '/shopping'
      preLoaderRoute: typeof ShoppingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/meals': {
      id: '/meals'
      path: '/meals'
      fullPath: '/meals'
      preLoaderRoute: typeof MealsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/goals': {
      id: '/goals'
      path: '/goals'
      fullPath: '/goals'
      preLoaderRoute: typeof GoalsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chores': {
      id: '/chores'
      path: '/chores'
      fullPath: '/chores'
      preLoaderRoute: typeof ChoresRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/calendar': {
      id: '/calendar'
      path: '/calendar'
      fullPath: '/calendar'
      preLoaderRoute: typeof CalendarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/assistant': {
      id: '/assistant'
      path: '/assistant'
      fullPath: '/assistant'
      preLoaderRoute: typeof AssistantRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AssistantRoute: AssistantRoute,
  CalendarRoute: CalendarRoute,
  ChoresRoute: ChoresRoute,
  GoalsRoute: GoalsRoute,
  MealsRoute: MealsRoute,
  SettingsRoute: SettingsRoute,
  ShoppingRoute: ShoppingRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
